CREATE TABLE IF NOT EXISTS sensor_readings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    feed_rate DECIMAL(8,2),
    water_flow DECIMAL(8,2),
    rpm DECIMAL(6,2),
    power DECIMAL(8,2),
    health_alarm TINYINT(1) DEFAULT 0
);

INSERT INTO sensor_readings (feed_rate, water_flow, rpm, power, health_alarm)
SELECT
    120 + RAND() * 40,
    30 + RAND() * 20,
    9.5 + RAND() * 2,
    1800 + RAND() * 700,
    RAND() < 0.05
FROM
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) a,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) b,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) c,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4) d;
